FEATURE_DESCRIPTIONS = {
    "X_ActualPosition": "X축 실제 위치",
    "X_ActualVelocity": "X축 실제 속도",
    "X_ActualAcceleration": "X축 실제 가속도",
    "X_SetPosition": "X축 참조 위치",
    "X_SetVelocity": "X축 참조 속도",
    "X_SetAcceleration": "X축 참조 가속도",
    "X_CurrentFeedback": "X축 전류 피드백",
    "X_DCBusVoltage": "X축 DC 버스 전압",
    "X_OutputCurrent": "X축 출력 전류",
    "X_OutputVoltage": "X축 출력 전압",
    "X_OutputPower": "X축 출력 파워",
    "Y_ActualPosition": "Y축 실제 위치",
    "Y_ActualVelocity": "Y축 실제 속도",
    "Y_ActualAcceleration": "Y축 실제 가속도",
    "Y_SetPosition": "Y축 참조 위치",
    "Y_SetVelocity": "Y축 참조 속도",
    "Y_SetAcceleration": "Y축 참조 가속도",
    "Y_CurrentFeedback": "Y축 전류 피드백",
    "Y_DCBusVoltage": "Y축 DC 버스 전압",
    "Y_OutputCurrent": "Y축 출력 전류",
    "Y_OutputVoltage": "Y축 출력 전압",
    "Y_OutputPower": "Y축 출력 파워",
    "Z_ActualPosition": "Z축 실제 위치",
    "Z_ActualVelocity": "Z축 실제 속도",
    "Z_ActualAcceleration": "Z축 실제 가속도",
    "Z_SetPosition": "Z축 참조 위치",
    "Z_SetVelocity": "Z축 참조 속도",
    "Z_SetAcceleration": "Z축 참조 가속도",
    "S_ActualPosition": "스핀들 실제 위치",
    "S_ActualVelocity": "스핀들 실제 속도",
    "S_ActualAcceleration": "스핀들 실제 가속도",
    "S_SetPosition": "스핀들 참조 위치",
    "S_SetVelocity": "스핀들 참조 속도",
    "S_SetAcceleration": "스핀들 참조 가속도",
    "S_CurrentFeedback": "스핀들 전류 피드백",
    "S_DCBusVoltage": "스핀들 DC 버스 전압",
    "S_OutputCurrent": "스핀들 출력 전류",
    "S_OutputVoltage": "스핀들 출력 전압",
    "S_OutputPower": "스핀들 출력 파워",
    "S_SystemInertia": "스핀들 토크 관성",
    "M_CURRENT_FEEDRATE": "현재 이송 속도",
}


def describe_feature(code: str) -> str:
    return FEATURE_DESCRIPTIONS.get(code, code)
